### ISSUE TITLE
No audio on streaming

### ISSUE THREAD

**Issue by SuperKali** [sipeed/NanoKVM#100]
Hi,

It's possible to add audio from hdmi port?

Thank you

**Comment by Z2Z-GuGu** [comment]
Hi, NanoKVM does not support this feature in hardware, and there is a possibility that USB Auido will be used in the future to achieve audio input and output (but don't have too much expectation)

**Comment by hardingt** [comment]
I know this is closed, I wanted to add my voice to this, I also would enjoy getting the most basic audio in/out and also would be interested in an upgraded version which does it over HDMI. From what I can tell, this is not a feature that is supported in most KVMs so it would set it apart as well.
