### ISSUE TITLE
Shipping question

### ISSUE THREAD

**Issue by Datexcz** [sipeed/NanoKVM#110]
Hi, on september 29 i preorder the Nanokvm. Here on the github page it says that the preorders should ship out mid october. But then i noticed that Aliexpress says the NanoKVM will be shipped on Nowember 30. So wheres the truth?

**Comment by Reletiv** [comment]
Mine now says December 31..... so far mid October yes indeed

**Comment by kiler129** [comment]
@Datexcz this is GitHub and not sales support. If you have questions about pre-sale orders you can e-mail them at `support@sipeed.com`.

**Comment by Zepan** [comment]
Hi, the Aug&Sep order will send out in Oct; the Oct order will send in Nov&Dec.
The newest 5Kpcs will start ship this weekend, most order before 10.1 will finish ship before 10.31

**Comment by jernejs** [comment]
I ordered mine in August, and received shipping notification yesterday (and according to tracking it's been shipped on Friday, and it's already in the country).

**Comment by wj-xiao** [comment]
Estimated shipping time:

| Purchase Time         | Shipping Time          |
|-----------------------|------------------------|
| July ~ September 24   | Before October 31      |
| September 25 ~ October 25 | November 15 ~ November 30 |
| October 26 ~ Now      | December               |
