### ISSUE TITLE
Swap NanoKVM's streaming service registration from NanoKVM lite to LicheeRV-Nano-WE

### ISSUE THREAD

**Issue by Michal4K** [sipeed/NanoKVM#114]
Is it possible to ask you to swap registration of NanoKVM's streaming service from NanoKVM Lite to LicheeRV-Nano-WE? I really wanted to DIY NanoKVM Lite with wifi, but I didn't realize this limitation. I know I could theoretically swap sg2002 on those boards, but before I will put my hot air soldering skills to test. I just try to ask.

**Comment by Z2Z-GuGu** [comment]
@Michal4K Hi, thanks for your support. Currently, we do not have a separate modification service, but in fact, the pins on both sides lead out all the necessary signals for connecting to the WiFi module. You can try DIY a KVM top board PCB with WiFi function. It maybe useful:  [LicheeRV Nano schematic](https://cn.dl.sipeed.com/shareURL/LICHEE/LicheeRV_Nano/02_Schematic) and [NanoKVM top board schematic](https://cn.dl.sipeed.com/shareURL/KVM/nanoKVM/HDK/02_Schematic) . Alternatively, you can [book](https://sipeed.com/nanokvm/pcie) our NanoKVM PCIe, which will provide a WiFi+ETH coexistence version. It is currently in production and will be available soon

**Comment by Z2Z-GuGu** [comment]
Personally I imagine that "NanoKVM WE" is really cool. Perhaps you can send them IDs (with using the  `cat /device_key` command) to my [email](z2zmoujietongxue@126.com), and I will replace it after receiving the email.

**Comment by Michal4K** [comment]
Thanks for help, i will close this issue.

**Comment by sunglee42** [comment]
according to the [latest information](https://github.com/sipeed/NanoKVM/issues/270#issuecomment-2603875433)
> note: In applications with an app version greater than 2.1.0, we use a server written in Go to complete video stream transmission. However, Go has difficulty accessing data from the chip's MIPI CSI -> VI -> VPSS -> VENC path. Therefore, I developed the kvm_vision application using MaixCDK, which allows the Go side to conveniently obtain encoded images through the generated libkvm.so dynamic library. The libkvm.so handles all the details but relies on an upstream encryption library. After version 2.2.0, we abandoned the design of the encryption library and replaced it with libkvm_mmf.so. All related code has been open-sourced in the components/ directory.

there are no `device_key` work needed to get `libmaxicam_lib.so` anymore

but official support has not been officially provided yet
so just let people know this was not a problem anymore(save time)
and we keep discuss in here #639
