### ISSUE TITLE
Image doesn't get updated in BIOS or Linux console

### ISSUE THREAD

**Issue by dulasau** [sipeed/NanoKVM#117]
Version 2.0.9
Everything works fine when an OS loaded (tried on different machines with Debian/Ubuntu), but whenever I enter BIOS or a machine loaded into Linux console image become static: image is not getting updated, only page refresh updates the image.

* Sometimes the image can get refreshed automatically after about 60 secs
* Frame Detect is disabled
* OLED Display shows 30FPS
* Tried different resolutions/FPS/Quality - the same result
* In a browser dev tool I can see that request /api/stream/mjpeg is working fine 
* HID is not connected, testing with an external keyboard
* Tested devices are 8th/12th/14th gen intel CPUs with iGPUs without any DisplayPort/VGA adapters 
 
It almost looks like "Frame Detect" is't "fully" disabled

**Comment by dulasau** [comment]
I've been playing with it entire day yesterday and it wasn't working, re-flashing didn't help either....
But I just turned it on and It magically started working!!!
I'll keep the issue open while keeping an eye on the device for a couple of more days just to be sure.

**Comment by dulasau** [comment]
It stopped working again (((((

**Comment by dulasau** [comment]
The problem seems to intermediate, most of the times it doesn't work, sometimes it does. Got the same problems once with Ubuntu desktop as well (((

**Comment by nwgat** [comment]
how did you connect power?

**Comment by dulasau** [comment]
Tried both options: through USB from the host machine and thought AUX USB port - the same behavior.

**Comment by dulasau** [comment]
Alrighty, after a lot of testing turned out that the problem seems to be related to my Unify (pro 48 poe) switch ..... Have no idea how/what/why:
* nanokvm gets an IP
* I can access Web UI, but no image update
* Works flawless with my Mikrotik routers/switches (even with CRS317 through SPF+ ethernet adapter)

If i connect nanokvm to unifi switch and boot it - most of the times it doesn't work (sometimes it does), re-connect it (without powering off) to a mikrotik switch - it starts working, connect it back to unifi switch (without powering off) - it's working.... Mystery
