### ISSUE TITLE
Is it possible to incorporate a DHCP server function?

### ISSUE THREAD

**Issue by ikutakanpani** [sipeed/NanoKVM#12]
Hello!

NanoKVM is a great product and I am satisfied with it

This is a very niche need, but is it possible to add a DHCP server function to NanoKVM?
I would like an IP address to be automatically assigned to the PC when the PC and NanoKVM are directly connected via LAN. This is because users cannot set a static IP address if their Windows PC does not have administrator privileges.

I think it is best to enable NanoKVM's DHPC server only from the command line, as this feature may cause conflicts if connected to a LAN that already has DHCP.

I'm sorry if it's hard to read because it was created using machine translation from Japanese.

**Comment by wj-xiao** [comment]
Please refer to the [document](https://wiki.sipeed.com/hardware/en/kvm/NanoKVM/network/static_ip.html).
