### ISSUE TITLE
NanoKVM does not boot: nothing on OLED display, PC-USB and AUX LEDs lit

### ISSUE THREAD

**Issue by mivens** [sipeed/NanoKVM#13]
I have just received a NanoKVM Full. 
It does not boot up. 
I have both the PC-USB and AUX USB ports connected and connected it to my ethernet switch.
There is a blue AUX LED and a red LED for the PC-USB lit on the side.
The blue 5V LED is lit on the side of the NanoKVM with the OLED screen.
But there is nothing on the OLED display and the ethernet port stays down.

I have tried multiple USB chargers as well as a USB power bank. 

Can anyone suggest next steps to troubleshoot?

<img width="236" alt="nanokvm-1" src="https://github.com/user-attachments/assets/d4364d4d-f4d9-4798-a3c6-a75072986af4">
<img width="392" alt="nanokvm-2" src="https://github.com/user-attachments/assets/55561b4c-0e66-404b-b973-7793f9a852c9">

**Comment by polyzium** [comment]
Hi, try flashing the latest firmware by following [this guide](https://github.com/sipeed/NanoKVM/issues/7#issuecomment-2288903849) and see if it works. If not, the SD card inside the KVM may be defective and you may need to replace it.

**Comment by Z2Z-GuGu** [comment]
Thank you for @polyzium 's reply. Please follow his steps to re burn the TF card. You can also refer to [disassembly]( https://wiki.sipeed.com/hardware/assets/NanoKVM/guide/fix1.png),[WiKi]((https://wiki.sipeed.com/hardware/en/kvm/NanoKVM/system/flashing.html) If the blue LED does not start flashing after burning, the NanoKVM-A board needs to be removed and powered on again (starting like the Lite version) to see if the blue LED is flashing.

**Comment by mivens** [comment]
Thank you - I wasn't sure if disassembling a newly received device was OK. 

After reflashing the TF card, the problem is resolved.
