### ISSUE TITLE
Keyboard and Mouse input not working

### ISSUE THREAD

**Issue by Arantis** [sipeed/NanoKVM#135]
Hey,

first of all thanks for the nice product i really like the idea. I've ordered 2 nanoKVM Lite and a Bunde NanoKVM.
For some reason i might not understand it but i can't get the keyboard or mouse input to work.

I unboxed it connected it with USB, Ethernet and HDMI. The device gets an IP and i can login. I can see the Screen of the device i try to control (i tried a TrueNAS - Terramaster and a Minisforum MS-01). 
As said i can see the device screen output but i can't input anything through either my own keyboard, paste or screen keyboard of the KVM. I can see the cursor blinking but the input does not work at all.
I've tried with Chrome, Firefox and also Edge all with the same result.

Am i doing something wrong or how can i get the input to work?

My Info:
mDNS kvm-7ef9.local
Image Version 2024-08-17-18-13-713161.img
Versionsnummer 2.1.0

Thanks,
Arantis

**Comment by Arantis** [comment]
Nevermind ... researched through the issue list here and found a solution that works for me as well.

The cable that got delivered with the nanoKVM are not working. Once i've tried a USB-C cable that i got here the keyboard works just fine so your cable you deliver are bad...

**Comment by CaneTLOTW** [comment]
I already exchange the cables. 
mouse is working some times, keyboard rarely...

Especially NOT after reboot of PC...

**Comment by fjbsantiago** [comment]
Amazing. Worked for me after switching to a modern USB-C to USB-A cable. USB-C connected to the NanoKVM, USB-A connected to the server.

**Comment by z88kat** [comment]
I just ran into the same problem. Those shipped cables are bad. Swapping them out fixed the issue.
