### ISSUE TITLE
Paste Content needs to support all symbols and letters

### ISSUE THREAD

**Issue by nwgat** [sipeed/NanoKVM#139]
trying to copy some powershell code like this
`$product_name = (Get-WmiObject Win32_BaseBoard).Product; echo "Product Name: $product_name";`
but it ends up very differently on the other machine  (see notepad in screenshot)
![chrome_VDKhtzCLZb](https://github.com/user-attachments/assets/f8218a2b-c247-4db4-a16c-261bcd6ba5c6)

**Comment by wj-xiao** [comment]
Could you please provide information about the input method on your remote host?

**Comment by nwgat** [comment]
> Could you please provide information about the input method on your remote host?

i almost figured it out, my other system was set to united states instead of united kingdom so it i set them to both united kingdom and norwegian bokmål as the keyboard layout it seem to copy the correct text, but the keys for `@` dont seem to work under nanokvm, if i connect via rustdesk i can use `alt gr + 2` for `@`
