### ISSUE TITLE
USB Device details

### ISSUE THREAD

**Issue by haggis-supper** [sipeed/NanoKVM#142]
I've been trying to figure out why the NanoKVM is not as stable as PiKVM for the USB devices. 

piKVM has the USB devices configured as a "Multifunction Composite Gadget" defined as a "Boot Interface Subclass" that works on every device i have used it on ( PC, Mac, into other microcontrollers.)

I've notice the NanoKVM has the devices configured differently. 

Possibly the attached USB information can help to fix the NanoKVM problems.

[nanoKVM.txt](https://github.com/user-attachments/files/17666496/nanoKVM.txt)
[pikvm.txt](https://github.com/user-attachments/files/17666497/pikvm.txt)

**Comment by Z2Z-GuGu** [comment]
Hello, the issue with NanoKVM USB instability is related to the quality of the USB cable. I have tested all the USB cables on the table and found that only one cable can maintain a stable connection when shaken. If you are also experiencing unstable connections, you can try replacing it with a better quality cable

**Comment by haggis-supper** [comment]
Ignore this, just downloaded the latest 2.1.0 code and it is a LOT better on a Mac Mini. Mouse and keyboard work a lot better and not so flakey. 
This is definately usable now.

**Comment by haggis-supper** [comment]
Closed
