### ISSUE TITLE
[FEATURE REQUEST] Turn on Mouse Jiggler when Idle

### ISSUE THREAD

**Issue by dw5** [sipeed/NanoKVM#158]
If user has enabled Mouse jiggler feature, It will allow to monitor the remotely connected device, by preventing it from getting into sleep mode or locking itself (plus would not require installation of additional software or purchase of USB jiggler)

PiKVM has an implementation, and it would be a great addition to NanoKVM. 
It will also allow me to buy more NanoKVMs thanks to not needing to buy a mouse jiggler too.

**Comment by alexislefebvre** [comment]
As a workaround, can you disable sleep mode on the monitored device?

**Comment by Snazzie** [comment]
This man just wants to auto jiggle his work laptop so his teams doesnt rat on him lmao

**Comment by lwbt** [comment]
> This man just wants to auto jiggle his work laptop so teams doesnt rat on him lmao

He could get that for a fraction of the price of a NanoKVM if it was that important to him.
Why trash talk a good idea and a useful feature?

**Comment by Snazzie** [comment]
> > This man just wants to auto jiggle his work laptop so teams doesnt rat on him lmao
> 
> He could get that for a fraction of the price of a NanoKVM if it was that important to him. Why trash talk a good idea and a useful feature?

take a joke, party pooper.

**Comment by dw5** [comment]
shout out to the spammers above

**Comment by RobbieL811** [comment]
Is there any way to disable this god forsaken feature? I tried disabling it in the gui. It's screwing with my games on my gaming desktop. Keeps taking over control from my controller. Disabling in the gui did nothing. Mouse continued to jiggle. I do not want this. I want my computer to sleep when it wants to and I can wake it when I need it. Hoping theres a command that can do away with this nonsense.

**Comment by civictd04** [comment]
> Is there any way to disable this god forsaken feature? I tried disabling it in the gui. It's screwing with my games on my gaming desktop. Keeps taking over control from my controller. Disabling in the gui did nothing. Mouse continued to jiggle. I do not want this. I want my computer to sleep when it wants to and I can wake it when I need it. Hoping theres a command that can do away with this nonsense.

Since this is a closed issue you might want to report it as a new issue.
