### ISSUE TITLE
server.yaml no longer working for https

### ISSUE THREAD

**Issue by michaelsage** [sipeed/NanoKVM#185]
Just updated to 2.1.2 and the override for https and certs is no longer working. I can access the gui on http, but not https I have checked the config with a 2.1.1 nano I am running and they are identical. Please advise!

**Comment by zucht** [comment]
After the 2.1.2 update, I experienced the same issue. After deleting the server.yaml file and restarting the system, I received a new server.yaml with more options than my original server.yaml. After modifying this file to use HTTPS and restarting the system again, it worked.

**Comment by michaelsage** [comment]
Thank you! That's fixed it for me. :)
