### ISSUE TITLE
PoE expansion accessory NanoKVM (Full)

### ISSUE THREAD

**Issue by mcury1985** [sipeed/NanoKVM#189]
Where can I find the PoE expansion accessory for the NanoKVM (Full) ?
I want to buy one.

Thanks.

**Comment by x-magic** [comment]
I don't think Lichee RV Nano supports PoE or expansion at all. 

You can use PoE splitters like [this one](https://www.amazon.com/dp/B087F4QCTR) as an alternative.

**Comment by mcury1985** [comment]
Oh, thanks.
I didn't know about these splitters, nice.

**Comment by mcury1985** [comment]
@x-magic Just to mention, I bought one and it is working flawlessly..
Actually bought 2, one for my raspberry pi 5 which is 5v 4A, and another one 5v 2.1A for the nanoKVM.
Thanks for the suggestion about that!! Bought them at Aliexpress.
