### ISSUE TITLE
Static IP address ?

### ISSUE THREAD

**Issue by madworm** [sipeed/NanoKVM#19]
Can the device be configured to use a static IP address?

That could be useful, especially for the one without a display.

**Comment by wj-xiao** [comment]
Please refer to the [static ip](https://wiki.sipeed.com/hardware/en/kvm/NanoKVM/network/static_ip.html).

If there is no display, you need to get the ip firstly. Refer to [this](https://wiki.sipeed.com/hardware/en/kvm/NanoKVM/system/updating.html#Obtain-IP-Address).

**Comment by madworm** [comment]
Apparently I'm blind.

Thanks !

**Comment by madworm** [comment]
Closing.
