### ISSUE TITLE
NanoKVM presence adds a default network interface on fresh ubuntu installs which make the machine unreachable

### ISSUE THREAD

**Issue by EcceGratum** [sipeed/NanoKVM#227]
I installed a fresh Kubuntu 24.04 on a machine which has NanoKVM plugged all the time.
I installed from a usbkey, not from NanoKVM virtual image feature.

I noticed on the first launch of the new install, that there was 2 network interfaces instead of one. One is for the physical LAN on the motherboard as expected and the other one appears to be interface to NanoKVM.
The network interface to NanoKVM is the one used by default which makes the machines unreachable from LAN and it can't connect to internet.

In my case, the network interface name is enxda248c27027c . 
I am trying to remove that extra interface but in the meantime i want to let people know about the issue

**Comment by archont94** [comment]
This is expected and can be disabled:
![image](https://github.com/user-attachments/assets/e659cb69-fd5f-4b3d-9885-a8f582cd6cfe)

**Comment by EcceGratum** [comment]
@archont94 Thank you
