### ISSUE TITLE
Boot on power?

### ISSUE THREAD

**Issue by rmoriz** [sipeed/NanoKVM#231]
Hi,

is it possible to make the NanoKVM boot when power to the device is supplied? Currently I have to press the power button manually.

Thanks

**Comment by ucki007** [comment]
Hi,

are you sure, your NanoKVM is connected correctly?

It should boot as soon as there is power provided via HID-USB or AUX-USB.

The power button is meant to control the power of the device you want to use your NanoKVM with (via USB ATX extension or directly connected to the corresponding pins on NanoKVM).
