### ISSUE TITLE
Azerty Alt-GR (Right Alt) not working for symbols like @

### ISSUE THREAD

**Issue by OrpheeGT** [sipeed/NanoKVM#27]
Hello

It seems there is only QWERTY supported ?

I'm on azerty keyboard, and typing with it inside nanokvm screen result as qwerty.

kind of tricky when trying to unlock computer session with password ******

Can it be addressed ?

Thank you

**Comment by Z2Z-GuGu** [comment]
Hi, we have tested and found that the keyboard layout settings in the system will affect your input characters. Please try modifying the keyboard layout in the settings of the controlled host.

**Comment by OrpheeGT** [comment]
Hi, I'm not sure to understand.

My controlled laptop is running with azerty keyboard under windows.

I'm running NanoKVM virtual screen inside a Linux Mint also with azerty keyboard layout.

But typing from Linux virtual screen from web browser seems to be in QWERTY, if I raise the virtual keyboard popup from web browser, it is also in QWERTY

**Comment by OrpheeGT** [comment]
Update, actually you are right.

I made a mistake, but it seems some keys are bad identified.

There is and @ in my password.

So I usually type on my AZERTY Keyboard : Atl-GR (right Alt) + 0 (à / @)

But it seems AltGR is not recognized.
I have to use : Left CTRL + Left Alt + 0 (à / @)
![image](https://github.com/user-attachments/assets/882c7804-a565-4b57-b3b1-59d48b8b060e)

![image](https://github.com/user-attachments/assets/71daa88d-046c-4a96-a02f-20000e3d1568)

**Comment by wj-xiao** [comment]
fixed in 2.0.9
