### ISSUE TITLE
Support for Rack Mount

### ISSUE THREAD

**Issue by SchoolGuy** [sipeed/NanoKVM#3]
Hey guys!

I recently learnt from a friend about this cool project. Is it possible to get a mounting bracket that attaches to a standard 19'' Rack? If you guys love the idea, maybe a 1U chassis with keystones for the 5-pack that is fed by a single power plug from the back of the chassis?

Regards,
SchoolGuy

**Comment by Zepan** [comment]
Thank you for your suggestion! we make a vote on twitter: https://x.com/SipeedIO/status/1814200599782576539
We will figure it out depend on vote result

**Comment by SchoolGuy** [comment]
@Zepan Thanks for creating the vote. Why not go with the cube form and offer an adapter that can be 3D printed? Then you probably get the best out of both worlds. Your micro cube form factor is a very awesome feature!

**Comment by Zepan** [comment]
wow, I see, we can make a 3D printed adapter, the OLED side outside~

**Comment by marv7000** [comment]
I agree with this, a rack mount adapter would be very cool
