### ISSUE TITLE
Ctrl + Ctrl not working

### ISSUE THREAD

**Issue by icq112771720** [sipeed/NanoKVM#32]
how to send Ctrl + Ctrl key input?

also composite key does not work.
ex)  Ctrl + Shift + 1

**Comment by polyzium** [comment]
Have you tried using the virtual keyboard?

**Comment by icq112771720** [comment]
![image](https://github.com/user-attachments/assets/87f71c8d-518c-4499-8084-71bb0a18aef2)
Ctrl + Shit +1 => ! 
Shit +1 => !
Ctrl + does not work.

**Comment by wj-xiao** [comment]
I've tested in Ubuntu and it seems to be expected behavior. Ctrl is ignored unless there's a specific event associated with the key combinations.

Such as Using Ctrl+C triggers the expected response.

**Comment by IsayIsee** [comment]
Some software requires double-clicking Ctrl to activate by default, such as Listary
