### ISSUE TITLE
NanoKVM Lite Power Button Trigger

### ISSUE THREAD

**Issue by beatles1** [sipeed/NanoKVM#34]
To be able to trigger the power button on the host with the NanoKVM Lite do we need any additional hardware. I can see pin A23 is for this but would that need to trigger a relay/transistor?

Additionally would it be possible to apply 5v somewhere as a secondary power supply or again does that need more hardware?

Thanks in advance.

**Comment by Z2Z-GuGu** [comment]
Hi, it need to use a solid state relay to control the computer power, and can't use the pins to directly connect to the power button, and we have open-sourced the circuit design of KVM Full [here](https://cn.dl.sipeed.com/shareURL/KVM/nanoKVM/HDK/02_Schematic) for reference.
In addition, 5V can be used to supply external power (which will simultaneously increase the burden on the power adapter), but the VBUS pin is preferred, and using VSYS may damage your NanoKVM.

**Comment by beatles1** [comment]
Oh thank you, that's really useful. Is there a reason you need a solid state relay rather than just an optocoupler? Does the power button actually carry much current?

**Comment by Z2Z-GuGu** [comment]
Optocouplers are theoretically feasible, but we were forced to use solid-state relays due to a hardware design mistake a long time ago, and later did not have enough time to validate the new schematic.

**Comment by beatles1** [comment]
Thank you, optocouplers just seem a lot cheaper to get only a few of. I'll have a play and see if I can get it to work.

For the 5V quesiton, am I understanding correctly that we can connect a 5V power supply to the VBUS and ground pins and that will power the NanoKVM?

**Comment by Z2Z-GuGu** [comment]
> For the 5V quesiton, am I understanding correctly that we can connect a 5V power supply to the VBUS and ground pins and that will power the NanoKVM?

Yeah, you're right, NanoKVM does not require too much power (approximately 1W), ensuring a power supply in the range of 4.5-5.5V is ok.

**Comment by chrismazanec** [comment]
I tested this, and it works well:
you need:
- 2x KAQV214 (1 per switch)
- 2x 330 ohm resitor
- some wires, soldering equipment

### schematics

<img width="1472" height="1120" alt="Image" src="https://github.com/user-attachments/assets/3d6a5bf5-daa0-4768-af26-6847f28ccd0f" />

### pin 1 identification on the KAQV214
The dot on the package marks pin 1. Holding the SSR with the dot in the top-left:

```
        Dot
        ↓
       ┌─────────┐
   1 ──┤●        ├── 6
   2 ──┤         ├── 5
   3 ──┤         ├── 4
       └─────────┘
```

<img width="8196" height="3865" alt="Image" src="https://github.com/user-attachments/assets/fd298dd8-2ea9-4a84-bd79-50d1657deda8" />

**Comment by Msprg** [comment]
Hello everyone,

@chrismazanec could I trouble you with a question? I am figuring this out with my own nanokvm lite units, and measuring the pins respective to the ground. The power key (503) is usually pulled down to ground and is pulled to 3v3 for a short duration on activation which seems to work as intended. What is more unclear to me is the rst key (507). Not only it is always pulled to 3v3 at all times, but pressing reset button in the interface ui does not seem to provoke any sort of change on this gpio.

After some more investigating it would seem that this gpio number doesn't even get exported as a device file on my two kvms that I tested this with:

``` shell
~ # ls -lsa /sys/class/gpio/
total 0
     0 drwxr-xr-x    2 root     root             0 Jun  5 09:00 .
     0 drwxr-xr-x   55 root     root             0 Jun  5 09:00 ..
     0 --w-------    1 root     root          4096 Jun  5 09:00 export
     0 lrwxrwxrwx    1 root     root             0 Jun  5 09:00 gpio451 -> ../../devices/platform/3021000.gpio/gpiochip1/gpio/gpio451
     0 lrwxrwxrwx    1 root     root             0 Jun  5 09:00 gpio502 -> ../../devices/platform/3020000.gpio/gpiochip0/gpio/gpio502
     0 lrwxrwxrwx    1 root     root             0 Jun  5 09:00 gpio503 -> ../../devices/platform/3020000.gpio/gpiochip0/gpio/gpio503
     0 lrwxrwxrwx    1 root     root             0 Jun  5 09:00 gpio504 -> ../../devices/platform/3020000.gpio/gpiochip0/gpio/gpio504
     0 lrwxrwxrwx    1 root     root             0 Jun  5 09:00 gpio505 -> ../../devices/platform/3020000.gpio/gpiochip0/gpio/gpio505
     0 lrwxrwxrwx    1 root     root             0 Jun  5 09:00 gpiochip352 -> ../../devices/platform/5021000.gpio/gpio/gpiochip352
     0 lrwxrwxrwx    1 root     root             0 Jun  5 09:00 gpiochip384 -> ../../devices/platform/3023000.gpio/gpio/gpiochip384
     0 lrwxrwxrwx    1 root     root             0 Jun  5 09:00 gpiochip416 -> ../../devices/platform/3022000.gpio/gpio/gpiochip416
     0 lrwxrwxrwx    1 root     root             0 Jun  5 09:00 gpiochip448 -> ../../devices/platform/3021000.gpio/gpio/gpiochip448
     0 lrwxrwxrwx    1 root     root             0 Jun  5 09:00 gpiochip480 -> ../../devices/platform/3020000.gpio/gpio/gpiochip480
     0 --w-------    1 root     root          4096 Jun  5 09:00 unexport
```

Could I please trouble you with verifying whether - and how - does the reset key gpio work in your case? At the very least the output of the `ls -lsa /sys/class/gpio/` on your system would be interesting to see.
