### ISSUE TITLE
Keyboard not detected?

### ISSUE THREAD

**Issue by waterytart** [sipeed/NanoKVM#4]
So, I'm connecting the NanoKVM to my server. The first time I tried, it worked. It has since offered an update to v1.9.1, and I also copied some .ISO files to its internal storage. Now I tried again, and I can't get it to connect the keyboard on the remote PC. It won't type anything, either direct keyboard input, or through the soft keyboard.

Is there any way to troubleshoot this?

**Comment by polyzium** [comment]
Funnily enough, I recently ran into the same problem, only to find that the USB connector wasn't all the way in.
However, it wouldn't hurt to take a look at your USB devices and see if the keyboard is recognized. On Linux, you need to type `lsusb` in the terminal and look for `flyingrtx licheervnano`. If there is such a device, you may have to click the mouse button in the webUI and select "Reset HID" several times. In other cases, you may need to restart the daemon (see [wiki](https://wiki.sipeed.com/hardware/zh/kvm/NanoKVM/3_user_guide.html#%E5%BC%82%E5%B8%B8%E6%81%A2%E5%A4%8D), use Google Translate) or even reboot the KVM completely (please note that it would send a reset signal for some reason if you have the Full version with the ATX-B board wired and plugged in).

The software is not mature yet, but they're slowly open sourcing it, so hopefully people can iron out such bugs.

**Comment by Z2Z-GuGu** [comment]
> So, I'm connecting the NanoKVM to my server. The first time I tried, it worked. It has since offered an update to v1.9.1, and I also copied some .ISO files to its internal storage. Now I tried again, and I can't get it to connect the keyboard on the remote PC. It won't type anything, either direct keyboard input, or through the soft keyboard.
> 
> Is there any way to troubleshoot this?

Hello, we have solved this problem in the last few app updates, you can update the app to 2.0.3 (or higher) in the web page and try again.

**Comment by Z2Z-GuGu** [comment]
> Funnily enough, I recently ran into the same problem, only to find that the USB connector wasn't all the way in. However, it wouldn't hurt to take a look at your USB devices and see if the keyboard is recognized. On Linux, you need to type `lsusb` in the terminal and look for `flyingrtx licheervnano`. If there is such a device, you may have to click the mouse button in the webUI and select "Reset HID" several times. In other cases, you may need to restart the daemon (see [wiki](https://wiki.sipeed.com/hardware/zh/kvm/NanoKVM/3_user_guide.html#%E5%BC%82%E5%B8%B8%E6%81%A2%E5%A4%8D), use Google Translate) or even reboot the KVM completely (please note that it would send a reset signal for some reason if you have the Full version with the ATX-B board wired and plugged in).
> 
> The software is not mature yet, but they're slowly open sourcing it, so hopefully people can iron out such bugs.

Thanks for the feedback, we reproduced this reboot issue and found it to be a hardware design mistake, if you have the tools for soldering, you can try adding 1K resistor pull-down to GND on the GPIO A23 and A27 pins (https://wiki.sipeed.com/hardware/zh/kvm/assets/NanoKVM/1_intro/NanoKVM_2.jpg) . And we'll fix this on the latest hardware.

**Comment by polyzium** [comment]
> > Funnily enough, I recently ran into the same problem, only to find that the USB connector wasn't all the way in. However, it wouldn't hurt to take a look at your USB devices and see if the keyboard is recognized. On Linux, you need to type `lsusb` in the terminal and look for `flyingrtx licheervnano`. If there is such a device, you may have to click the mouse button in the webUI and select "Reset HID" several times. In other cases, you may need to restart the daemon (see [wiki](https://wiki.sipeed.com/hardware/zh/kvm/NanoKVM/3_user_guide.html#%E5%BC%82%E5%B8%B8%E6%81%A2%E5%A4%8D), use Google Translate) or even reboot the KVM completely (please note that it would send a reset signal for some reason if you have the Full version with the ATX-B board wired and plugged in).
> > The software is not mature yet, but they're slowly open sourcing it, so hopefully people can iron out such bugs.
> 
> Thanks for your feedback, we reproduced this reboot issue and found it to be a hardware design mistake, if you have the tools for soldering, you can try adding 1K resistor pull-down to GND on the GPIO A23 and A27 pins (https://wiki.sipeed.com/hardware/zh/kvm/assets/NanoKVM/1_intro/NanoKVM_2.jpg) . And we'll fix this on the latest hardware.

Just to be clear, you're showing the pinout of the LicheeRV Nano, which is what the Lite version is based on, do I have to do the same for the Full version considering that the ATX board is separate and the Full version is some sort of a "cluster" on top of the LicheeRV Nano base board?

**Comment by Z2Z-GuGu** [comment]
> > Thanks for your feedback, we reproduced this reboot issue and found it to be a hardware design mistake, if you have the tools for soldering, you can try adding 1K resistor pull-down to GND on the GPIO A23 and A27 pins (https://wiki.sipeed.com/hardware/zh/kvm/assets/NanoKVM/1_intro/NanoKVM_2.jpg) . And we'll fix this on the latest hardware.
> 
> Just to be clear, you're showing the pinout of the LicheeRV Nano, which is what the Lite version is based on, do I have to do the same for the Full version considering that the ATX board is separate and the Full version is some sort of a "cluster" on top of the LicheeRV Nano base board?

I made a simple example of pulling the two pins to GND with the 1.5K resistor on hand, which can be referred to in this diagram 
![](https://img.picui.cn/free/2024/08/21/66c5c39a04900.jpg)

**Comment by polyzium** [comment]
Understood, I'll give this a try when I get the chance

**Comment by Dark-Existed** [comment]
> > > Thanks for your feedback, we reproduced this reboot issue and found it to be a hardware design mistake, if you have the tools for soldering, you can try adding 1K resistor pull-down to GND on the GPIO A23 and A27 pins (https://wiki.sipeed.com/hardware/zh/kvm/assets/NanoKVM/1_intro/NanoKVM_2.jpg) . And we'll fix this on the latest hardware.
> > 
> > 
> > Just to be clear, you're showing the pinout of the LicheeRV Nano, which is what the Lite version is based on, do I have to do the same for the Full version considering that the ATX board is separate and the Full version is some sort of a "cluster" on top of the LicheeRV Nano base board?
> 
> I made a simple example of pulling the two pins to GND with the 1.5K resistor on hand, which can be referred to in this diagram ![](https://camo.githubusercontent.com/f65a0dbd7e1de4d9c61245070a4ab5ebba0b0229c0ecccb922c472512405aa1c/68747470733a2f2f696d672e70696375692e636e2f667265652f323032342f30382f32312f363663356333396130343930302e6a7067)

Is the diagram missing? For me, I am not that familiar with the hardware, Add a detail diagram please.
@Z2Z-GuGu

**Comment by Z2Z-GuGu** [comment]
@Dark-Existed 

I'm very sorry, there are some problems with the image bed that I uploaded before, which caused the image to not be displayed, so I re-uploaded the image: ![](https://img.picui.cn/free/2024/09/26/66f4bbb3cab1a.jpg)

**Comment by Z2Z-GuGu** [comment]
Unfortunately, on some older versions of hardware, even if the RESET control pin is pulled down with a resistor, it cannot solve the restart problem. The only solution is to disconnect the RESET jumper. The pull-down resistor is only effective for the power on/off button, so there will be no additional operation on the computer's power button when rebooting NanoKVM. I will update the explanation on the wiki later
