### ISSUE TITLE
Has anyone received their order yet?

### ISSUE THREAD

**Issue by corndog2000** [sipeed/NanoKVM#46]
I've emailed Sipeed twice about the status of my order. I have not heard back from them. Is this product legit, or should I try and get a refund through PayPal?

**Comment by pdostal** [comment]
I did receive out of nowhere last week. I'm in Czechia - Central Europe.

**Comment by polyzium** [comment]
If you used the pre-order page, this is probably why. I received mine via AliExpress within 9 days. Regardless, Sipeed's neglect of pre-orders seems deeply concerning.

**Comment by patschi** [comment]
I ordered mine via Aliexpress 4 weeks ago and received nothing yet. But from what I heard, they're shipping based on the date of ordering and expect to send out all before end of September.

They received approx. 2000 orders on Aliexpress in the last ~1.5 months I believe, so possibly a bit overwhelmed with the amount of orders as they are a small (?) team.

**Comment by polyzium** [comment]
Sounds like a plausible scenario. A lot of people are looking at the product, given the aggressive price point compared to the PiKVM.

**Comment by ccdoggy** [comment]
Reach out to support@sipeed.com if it was a preorder and has been a long time, I pre-ordered July 15th and just received it yesterday (US) which is just shy of 2 months.  Support was helpful and gave me tracking info.  Its clear they are doing their best to manufacture a fairly unique product with relatively high demand while also developing it further.

**Comment by TheSp1der** [comment]
I was also worried that I had tossed my cash into the ether, but these things are legit. They really are wonderful little devices and seem to work well. I was like you and also questioned why it was taking so long to receive them, it took a few days form them to get back to me when I inquired as to my order status (support@sipeed.com), but they did eventually reply with a tracking number. If you do ask them for a status try to include all your preorder details in the message.

**Comment by corndog2000** [comment]
I've emailed support twice with my order information. No reply after a week.

**Comment by egallis31** [comment]
received mine out of nowhere today - west coast us

**Comment by corndog2000** [comment]
Support finally responded saying my pre-order would ship mid to late October.
