### ISSUE TITLE
download lib failed

### ISSUE THREAD

**Issue by dcompagn** [sipeed/NanoKVM#49]
Hi, 

I've got the NanoKVM Lite. 
I flashed the SD card with the firmware v1.2.0 but the video capture is not working. 
Then, I run the `update-nanokvm.py` script but I got this error

`download firmware...`
`download from https://cdn.sipeed.com/nanokvm/latest.zip?n=1726304869`
`download firmware done`
`download lib...`
`update failed`
`download lib failed, content_type: application/json; charset=utf-8` 

Digging into the script I see that a device key is used as part of the request in the URL `"https://maixvision.sipeed.com/api/v1/nanokvm/encryption?uid={device_key}"`

The device key is read from `/device_key` which is in turn generated by reading `/sys/class/cvi-base/base_uid`

The error message I get is "encrypt failed":
`application/json; charset=utf-8, b'{"code":-2,"msg":"encrypt failed"}'`

Is this a server side mechanism to check if the HW is registered and provides selectively the upgrade of libs?

In this case my device_key is not working.

**Comment by wj-xiao** [comment]
You are right. Apologize for the issue.
Could you please provide your device key?

You can get the device key by executing `cat /device_key`.

**Comment by bfayers** [comment]
> You are right. Apologize for the issue. Could you please provide your device key?
> 
> You can get the device key by executing `cat /device_key`.

I've got the same issue with `d1c15bae1526b59a`

**Comment by wj-xiao** [comment]
@bfayers Sorry for that. The device key has been added. Please try again.

**Comment by TharsisZen** [comment]
Same issue with 2 separate new devices delivered a few days ago.
Lite: d1ca1f0c1359c262
Full: d1c188ba1526b59a

**Comment by dcompagn** [comment]
Hi, this is my device key.
`d1c11b1b1526b59a`

**Comment by wj-xiao** [comment]
@dcompagn Added. Please try again.

**Comment by Evs91** [comment]
this is mine; if you could check for it
`d1ccc40f1359c262`

**Comment by Kellanji** [comment]
Hi!
My device key is d1ccca1d1359c262

**Comment by muness** [comment]
Hi, my device key is `d1be23991359c262`. Can you add it, @wj-xiao ? Thanks!

**Comment by Finalemu** [comment]
I have the same problem. My device id is d1c1913c1526b59a
