### ISSUE TITLE
IPv6

### ISSUE THREAD

**Issue by Gunni** [sipeed/NanoKVM#55]
I cannot find it in the specs, does this device support IPv6?

Does it function without IPv4?

If no, why not?

**Comment by lion7** [comment]
I can confirm it works with IPv6. Received my NanoKVM yesterday and it works straight out of the box in a dual-stack network on both IPv4 and IPv6 addresses.

**Comment by hardillb** [comment]
Likewise I only see link-local IPv6 addresses

**Comment by kedama222** [comment]
I noticed that the file `/etc/sysctl.d/99-tailscale.conf` contains the setting:
`net.ipv6.conf.all.forwarding = 1`.

While this configuration is documented on [Tailscale's How-to Guides](https://tailscale.com/kb/1019/subnets#enable-ip-forwarding) as part of enabling subnet routing, I believe NanoKVM is not primarily intended to function as a subnet router.

**Comment by kedama222** [comment]
related #197

**Comment by wj-xiao** [comment]
Please check #297
