### ISSUE TITLE
no /dev/net/tun device for tailscale

### ISSUE THREAD

**Issue by lidless-eye** [sipeed/NanoKVM#6]
unlike to description in _/etc/init.d/S98tailscaled_, /dev/net/tun device is missing.
users have to set FLAGS="--tun=userspace-networking" to run tailscaled daemon.

modprobe tun also fails.
either new kernel with TUN or fix in init script is required.

tested with nanokvm app 2.0.4

**Comment by wj-xiao** [comment]
An image upgrade is required. 
The 1.0.0 image doesn't have Tailscale support. Please update to the latest version [1.2.0](https://github.com/sipeed/NanoKVM/releases/tag/v1.2.0).

**Comment by polyzium** [comment]
See [this Chinese wiki page](https://wiki.sipeed.com/hardware/zh/kvm/NanoKVM/4_firmware.html) (use Google Translate) on how to upgrade your firmware

**Comment by lidless-eye** [comment]
with new image, confirmed /dev/net/tun exists. thanks!
