### ISSUE TITLE
Main app running from /tmp ?

### ISSUE THREAD

**Issue by ddscentral** [sipeed/NanoKVM#67]
More of a question than an issue, do drop me a link if there's a better place to ask this.

Is there a reason the server and streaming apps are executed from /tmp instead of their native location of /kvmapp ?
/tmp resides in RAM and the device only has 128 MB accessible. The apps in /tmp take quite a sizeable chunk of this.

**Comment by FlorianHeigl** [comment]
not knowing the original reasons for it and I haven't taken a peek at this yet, but launching them from a ramdisk can mean the service doesn't die as easily on SD card failure. not as nice as booting to ram or so, but for 128M it can be a good choice for resilience.

**Comment by wj-xiao** [comment]
> Is there a reason the server and streaming apps are executed from /tmp instead of their native location of /kvmapp ?

The services are executed from /tmp to avoid file corruption and potential service outages. 
You can review and modify the startup method by this script `/etc/init.d/S95nanokvm`. 

> /tmp resides in RAM and the device only has 128 MB accessible. The apps in /tmp take quite a sizeable chunk of this.

128MB of memory is allocated to the kernel. This might be adjusted in the future to allocate more memory to the user.
