### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by polyzium** [sipeed/NanoKVM#74]
This repository currently has no license.
From https://choosealicense.com/no-permission/:
> If you find software that doesn’t have a license, that generally means you have no permission from the creators of the software to use, modify, or share the software. Although a code host such as GitHub may allow you to view and fork the code, this does not imply that you are permitted to use, modify, or share the software for any purpose.

Judging by the contributions so far and the recent stance on clones, I suggest going with GPLv3 (unless there is some proprietary code involved, in which case a cleanup/rewrite is needed). **Please note that you would have to ask all contributors who have contributed to this repository for an approval on relicensing.**

**Comment by wj-xiao** [comment]
Updated.
