### ISSUE TITLE
support@sipeed.com does not exist, unable to contact support for delivery status.

### ISSUE THREAD

**Issue by saildot4k** [sipeed/NanoKVM#75]

**Comment by Zepan** [comment]
hi, the mail will reply in 2 work day (10.1~10.7 is national holiday), what is your email address?

**Comment by saildot4k** [comment]
I emailed weeks ago but again email bounced back. As expected from a fly by
night Chinese company. Paypal just refunded me today due to non
communication on your part.

**Comment by patschi** [comment]
I sent them an email to exactly this address on 4th of September and received a helpful reply just 11 hours later. Can't complain. Looks like it's a problem on your end or from your mail provider then.

You could have used GitHub issue, their (granted, weird) forum or any other contact method on their wiki way earlier.

When briefly searching on the internet, it looks like Sipeed was funded around 2015-2018 and does have around 12 different products (and probably a smaller team of enthusiasts to manage them) - so not really "fly by night". But in any case, the company seems to be more mature than this insulting comment.
