### ISSUE TITLE
PC won't boot if PC-USB cable is connected to the PC.

### ISSUE THREAD

**Issue by mcury1985** [sipeed/NanoKVM#77]
The title says it all, it seems to be a short, not sure.
As soon as I unplug the PC-USB cable from the PC usb port, it boots perfectly.

Anyone knows what to do ?

edit:
It was indeed a short, fixed with a 3M electrical tape
You can close this issue, and btw, thanks very much for this product !!

edit2: Spoke to soon, it is happening again..
Fixed by enabling ErP in BIOS, S4 and S5.

**Comment by alexislefebvre** [comment]
See:

- https://github.com/sipeed/NanoKVM/issues/40#issuecomment-2336927509

**Comment by mcury1985** [comment]
> Is it the same issue than this one?
> 
>     * [Power to host via 5V USB? #40 (comment)](https://github.com/sipeed/NanoKVM/issues/40#issuecomment-2336927509)

That is it.. exactly.
By killing USB ports in the desktop, it boots perfectly. So it confirms that there is a reverse current preventing the board to boot.

I'm reading that topic to see what is going to be my next action. Perhaps mod the USB cable will be easier for me..

**Comment by mcury1985** [comment]
Just modded the USB cable, everything is working now with both cables connected, PC-USB and AUX power.
PC-USB PIN 1 with an electrical tape did the job.

**Comment by mcury1985** [comment]
I'm closing this, thanks @alexislefebvre
