### ISSUE TITLE
Tailscaled gets killed with OOM

### ISSUE THREAD

**Issue by kaspergrubbe** [sipeed/NanoKVM#89]
I experience that Tailscaled gets killed due to OOM:

> [49461.739303] Out of memory: 
> Killed process 2004 (tailscaled) total-vm:1313600kB, anon-rss:34604kB, file-rss:8kB, shmem-rss:0kB, UID:0 pgtables:292kB oom_score_adj:0

Is there any tweaking to be done?

**Comment by afro-coder** [comment]
I wonder if you can use this
https://tailscale.dev/blog/libtailscale

But I would definitely take a profile dump of tailscale

See the steps here
https://github.com/tailscale/tailscale/issues/9864

I wonder if their embedded image has lower memory usage.
https://tailscale.com/kb/1207/small-tailscale

https://tailscale.com/kb/1109/devices-without-tailscale

**Comment by rallisf1** [comment]
> I wonder if their embedded image has lower memory usage.
> https://tailscale.com/kb/1207/small-tailscale

Combining the daemon with the client just uses less storage, you still have to run it "twice" thus no improvements in memory. The important part here is compiling with the `--extra-small` flag. You lose some features (including debug messages), but it should also use less memory.

```bash
GOARCH=riscv64 GOOS=linux ./build_dist.sh --extra-small tailscale.com/cmd/tailscale
GOARCH=riscv64 GOOS=linux ./build_dist.sh --extra-small tailscale.com/cmd/tailscaled
```

Unfortunately; I don't have a NanoKVM yet to test this, so feel free to test it and report back.

**Comment by kaspergrubbe** [comment]
@majoracehole The log I showed is from the command `dmesg` that you can get to if you ssh into the device.

**Comment by majoracehole** [comment]
Aha yep exactly the same...!

`[ 2700.492728] oom-kill:constraint=CONSTRAINT_NONE,nodemask=(null),task=tailscaled,pid=1276,uid=0`
`[ 2700.492780] Out of memory: Killed process 1276 (tailscaled) total-vm:1314096kB, anon-rss:47204kB, file-rss:108kB, shmem-rss:0kB, UID:0 pgtables:260kB oom_score_adj:0`
`[ 2700.522872] oom_reaper: reaped process 1276 (tailscaled), now anon-rss:0kB, file-rss:0kB, shmem-rss:0kB`

**Comment by wj-xiao** [comment]
In the next version, we will adjust the memory allocation ratio to increase the amount of user memory.

**Comment by lwbt** [comment]
> In the next version, we will adjust the memory allocation ratio to increase the amount of user memory.

For anyone wondering get it here: https://github.com/sipeed/NanoKVM/releases/tag/v1.3.0

> 3. Expand user space RAM from 128MB to 158MB

Or any version than that is more recent than v1.3.0 from the releases page. At the moment I'm not sure how updates from inside the application relate to image updates. I had to download and install the image from above to get rid of Tailscale OOM kills.

**Comment by kaspergrubbe** [comment]
After updating to the latest version 2.1.2 I am no longer seeing any OOMs. 

I'm not really sure why my device says it's running version 2.1.2 when the newest release is 1.3.0, maybe I am in the future :) <img width="346" alt="Screenshot 2024-12-12 at 13 38 24" src="https://github.com/user-attachments/assets/1dcc9661-b74c-4a47-9f5e-12caf3f83c83" />

**Comment by lwbt** [comment]
> After updating to the latest version 2.1.2 I am no longer seeing any OOMs. 
> 
> I'm not really sure why my device says it's running version 2.1.2 when the newest release is 1.3.0

Application version (2.1.2) != Image version (1.3.0). FYI.
